In [2]:
#code to import a csv and convert it to a numpy array
#import the numpy library
import numpy as np
#open the file
raw_data = open("titanic.csv")
# load the CSV file as a numpy matrix

dataset = np.loadtxt(raw_data, delimiter=",")
#'shape' is the dimensions of the matrix
print(dataset.shape)

# separate the data from the target attributes
X = dataset[:,0:3]
y = dataset[:,3]
print(X)
print(y)


(2201, 4)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 ..., 
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
[ 1.  1.  1. ...,  0.  0.  0.]


In [3]:
from sklearn import datasets
import random
import statistics

from sklearn.cross_validation import train_test_split
tree_list = []
neighbors_list = []
ensemble_list = []

counter = 0 

while counter < 10:
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)

    from sklearn import tree
    tree_classifier = tree.DecisionTreeClassifier();
    tree_classifier = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier.predict(X_test)

    from sklearn.metrics import accuracy_score
    percent = (accuracy_score(tree_predictions, y_test))
    #print(percent)
    new_per = float(100*percent)
    tree_list.append(new_per)
    #print(str(new_per)+"%")

    from sklearn import neighbors
    knn_classifier = neighbors.KNeighborsClassifier()
    knn_classifier = knn_classifier.fit(X_train, y_train)
    knn_predictions = knn_classifier.predict(X_test)

    from sklearn.metrics import accuracy_score
    percent_two = (accuracy_score(knn_predictions, y_test))
    #print(percent_two)
    new_per_two = float(100*percent_two)
    neighbors_list.append(new_per_two); 
    #print(str(new_per_two)+"%")

    from sklearn import ensemble
    rf_classifier = ensemble.RandomForestClassifier()
    rf_classifier = rf_classifier.fit(X_train, y_train)
    rf_predictions = rf_classifier.predict(X_test)

    from sklearn.metrics import accuracy_score
    percent_three = (accuracy_score(rf_predictions, y_test))
    #print(percent_three)
    new_per_three = float(100*percent_three)
    ensemble_list.append(new_per_three)
    #print(str(new_per_three)+"%")
    
    counter = counter + 1

print(statistics.mean(tree_list)); 
print(statistics.mean(neighbors_list));
print(statistics.mean(ensemble_list)); 



79.07356948228883
73.13351498637601
78.99182561307902


After running each training module ten times, with unique values, I concluded that each test had an accuracy score of around 70% to 80%. After running this section multiple times, I found that both the Random Forest and Tree methods are more accurate than the Neighbors method. Neighbors typically returned an accuracy score in the low 70%s. Both Random Forest and Three ran an accuracy score in the upper 70%s. These two results where very identical. I decided to use Random Forest for my main method of prediction. I chose random forest over tree because Random Forest uses multiple algorithims, training sets and prediction codes (hence forest), while the tree module only has access to one. 

In [4]:
from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict([[3,1,1]])
#print(rf_predictions);
print("Printing results for an adult male in lower class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

Printing results for an adult male in lower class...
This person most likley died.


In [5]:
from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict([[1,1,0]])
#print(rf_predictions);
print("Printing results for an adult female in first class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

Printing results for an adult female in first class...
This person most likley survived.


In [6]:
from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict([[1,0,0]])
#print(rf_predictions);
print("Printing results for a female child in first class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

Printing results for a female child in first class...
This person most likley survived.


After running my experiment, I conducted some research on who was saved first on the titanic. I found that Women and children where saved before men. I also found that people in first class where often evacuated before the people in middle and lower class. 

In [35]:
raw_data = open("titanic.csv")

dataset_two = np.loadtxt(raw_data, delimiter=",")
print(dataset_two.shape)

X_train = dataset_two[:,0:2]
y_train = dataset_two[:,3]

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict([[1,1]])
#print(rf_predictions);
print("Printing results for an adult in first class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")
     
from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[1,0]])
#print(rf_predictions);
print("Printing results for a child in first class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[2,1]])
#print(rf_predictions);
print("Printing results for an adult in middle class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[2,0]])
#print(rf_predictions);
print("Printing results for a child in middle class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[3,1]])
#print(rf_predictions);
print("Printing results for an adult in lower class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[3,0]])
#print(rf_predictions);
print("Printing results for a child in lower class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

#from sklearn import ensemble

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
test = (accuracy_score(rf_predictions, y_test))
print(test)


(2201, 4)
Printing results for an adult in first class...
This person most likley survived.
Printing results for a child in first class...
This person most likley survived.
Printing results for an adult in middle class...
This person most likley died.
Printing results for a child in middle class...
This person most likley survived.
Printing results for an adult in lower class...
This person most likley died.
Printing results for a child in lower class...
This person most likley survived.
0.77565849228


In this section, I analyzed age and class. These results indicate that adults and children in first class where likley to survive. The data also reveals that children in every class had a higher chance of surviving than adults in all classes. 

In [36]:
raw_data = open("titanic.csv")

dataset_three = np.loadtxt(raw_data, delimiter=",")
print(dataset_three.shape)

X = dataset_three[:,1:3]
y = dataset_three[:,3]
#print(X)
#print(y)

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[1,1]])
#print(rf_predictions);
print("Printing results for an adult male")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")
     
from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[1,0]])
#print(rf_predictions);
print("Printing results for an adult female...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[0,1]])
#print(rf_predictions);
print("Printing results for a male child...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")
    

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[0,0]])
#print(rf_predictions);
print("Printing results for a female child...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
test = (accuracy_score(rf_predictions, y_test))

print(test)

(2201, 4)
Printing results for an adult male
This person most likley died.
Printing results for an adult female...
This person most likley survived.
Printing results for a male child...
This person most likley died.
Printing results for a female child...
This person most likley survived.
0.764759309718


This tested results between age and gender. I found that in this set, all men where predicted to die and all women where predicted to survive. After analyzing the first section, I am noticing the strong correlation between gender and survival. 

In [39]:
raw_data = open("titanicmid.csv")

dataset_four = np.loadtxt(raw_data, delimiter=",")
print(dataset_four.shape)

X_train = dataset_four[:,0:2]
y_train = dataset_four[:,2]

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict([[0,0]])
#print(rf_predictions);
print("Printing results for a female crew member...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")
     
from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[0,1]])
#print(rf_predictions);
print("Printing results for a male crew member...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[1,0]])
#print(rf_predictions);
print("Printing results for first class female...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[1,1]])
#print(rf_predictions);
print("Printing results for a first class male...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[2,0]])
#print(rf_predictions);
print("Printing results for female in middle class...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[2,1]])
#print(rf_predictions);
print("Printing results for a male in middle class ...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[3,0]])
#print(rf_predictions);
print("Printing results for a female in lower class ...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X, y)
rf_predictions = rf_classifier.predict([[3,1]])
#print(rf_predictions);
print("Printing results for a male in lower class ...")
if str(rf_predictions) == "[ 1.]":
    print("This person most likley survived.");
else:
    print("This person most likley died.")

#from sklearn import ensemble

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
test = (accuracy_score(rf_predictions, y_test))
print(test)

(2201, 3)
Printing results for a female crew member...
This person most likley survived.
Printing results for a male crew member...
This person most likley died.
Printing results for first class female...
This person most likley survived.
Printing results for a first class male...
This person most likley died.
Printing results for female in middle class...
This person most likley survived.
Printing results for a male in middle class ...
This person most likley died.
Printing results for a female in lower class ...
This person most likley survived.
Printing results for a male in lower class ...
This person most likley died.
0.77838328792


This final section looks at class and gender. This final section showed the notable importance of gender for determining survival. These results show that all females, regardless of there status as crew or class, where predicted to survive on the titanic. The data shows that regardless of crew position or class, all males where predicted to die. In conclusion for this section, I found that gender was the biggest determining factor in predicting whether someone on board the titanic would survive or not. 

In conclusion, I found that there are many ways to predict an outcome of an event using certain variables. I am curious to learn how the computer sorts data and determines an outcome. I am still unsure on the process of testing a sample's accuracy score when one line (varibale) is removed from the test data. I got many index mismatch errors. Because I was confused by the accuracy scores in this section, I also ran each possible outcome for each section when one variable was removed. From these outcomes, I was able to find and identify trends in data. 

In this project, I learned how to use pre-programmed machine learning to calculate the outcome of an event. I also learned how to take an apply an accuracy score to a data set to determine the accuracy of the machine prediction. While there are many public prediction methods available for use, there are cases where a specific model may be better than another model. It is important to check the prediciton accuracy or each model before choosing the appropriate machine learning method to use.  

Within the project, I was suprised that gender was the most determining factor in predicting whether or not a passanger survived. I had initially thought that children would have the highest survival rate amongst the passangers. This hypothesis was disproved in my variable tests, where I found that male children where predicted to die while female children where predicted to survive. 